import mongoose from "mongoose";
// Corrected the import of ObjectId. It's better to use mongoose.Schema.Types for ObjectId.
const { ObjectId } = mongoose.Schema.Types;

const DeliverySchema = new mongoose.Schema(
  {
    _id: ObjectId, // Using ObjectId as the primary key, auto-generated by Mongoose.

    // Delivery ID is a string identifier for each delivery.
    deliveryId: { type: String, required: true }, // Made 'deliveryId' required to ensure every delivery has a unique ID.

    customerId: {
      type: ObjectId,
      ref: "User", // Reference to the User collection for customer details.
      required: true,
    },

    businessId: {
      type: ObjectId,
      ref: "Business", // Reference to the Business collection for business details.
      required: true,
    },

    riderId: {
      type: ObjectId,
      ref: "User", // Reference to the User collection for rider details.
      required: true,
    },

    packageDetails: {
      type: {
        type: String,
        enum: ["small", "food", "documents", "heavy"],
        required: true,
      },
      description: { type: String, required: true }, // Required to ensure package description is always available.
      weight: { type: Number, required: true }, // Weight of the package in kg, set as required for consistency.
      dimensions: {
        length: { type: Number, required: true }, // Made dimensions required for every package to prevent null data.
        width: { type: Number, required: true },
        height: { type: Number, required: true },
      },
      notes: String,
      value: { type: Number, required: true }, // Declared value for insurance, mandatory for coverage tracking.
    },

    locations: {
      pickup: {
        address: { type: String, required: true },
        coordinates: {
          type: { type: String, enum: ["Point"], required: true },
          coordinates: { type: [Number], required: true },
        },
        contact: {
          name: { type: String, required: true },
          phone: { type: String, required: true },
        },
        instructions: String,
      },
      dropoff: {
        address: { type: String, required: true },
        coordinates: {
          type: { type: String, enum: ["Point"], required: true },
          coordinates: { type: [Number], required: true },
        },
        contact: {
          name: { type: String, required: true },
          phone: { type: String, required: true },
        },
        instructions: String,
      },
    },

    pricing: {
      baseFare: { type: Number, required: true },
      distanceFare: { type: Number, required: true },
      weightSurcharge: { type: Number, required: true },
      totalAmount: { type: Number, required: true },
      platformCommission: { type: Number, required: true },
      riderEarnings: { type: Number, required: true },
      businessEarnings: { type: Number, required: true },
    },

    // Status tracking to track the delivery process
    status: {
      current: {
        type: String,
        enum: [
          "pending",
          "accepted",
          "assigned",
          "picked_up",
          "in_transit",
          "delivered",
          "cancelled",
          "failed",
        ],
        required: true, // Current status is a mandatory field.
      },
      history: [
        {
          status: { type: String, required: true }, // Ensures status history always contains status.
          timestamp: { type: Date, required: true }, // Timestamp for each status update.
          actor: {
            type: String,
            enum: ["system", "customer", "business", "rider"],
            required: true,
          }, // Actor performing status change.
          location: { lat: { type: Number }, lng: { type: Number } },
        },
      ],
    },

    tracking: {
      route: [
        {
          lat: { type: Number, required: true },
          lng: { type: Number, required: true },
          timestamp: { type: Date, required: true },
          speed: { type: Number, required: true },
        },
      ],
      distance: { type: Number, required: true }, // Distance in km, required for accurate delivery tracking.
      estimatedTime: { type: Number, required: true }, // Estimated time in minutes, must be provided for route planning.
      actualTime: { type: Number, required: true }, // Actual time in minutes, for delivery tracking.
    },

    proofOfDelivery: {
      type: {
        type: String,
        enum: ["photo", "pin", "signature"],
        required: true, // Ensuring a valid proof type is provided.
      },
      value: { type: String, required: true }, // Proof of delivery, either URL, PIN, or signature data, required for validation.
      timestamp: { type: Date, required: true }, // Timestamp for when proof was provided.
    },

    payment: {
      method: {
        type: String,
        enum: ["cash", "card", "transfer"],
        required: true, // Payment method is required to know how payment was made.
      },
      status: {
        type: String,
        enum: ["pending", "completed", "failed", "refunded"],
        required: true, // Payment status is crucial for transaction tracking.
      },
      transactionId: { type: String, required: true }, // Transaction ID for payment tracking, must be unique and required.
      paidAt: { type: Date, required: true }, // Timestamp of when payment was made.
    },

    ratings: {
      rider: {
        stars: { type: Number, required: true }, // Rating of the rider, required for feedback.
        comment: { type: String },
        timestamp: { type: Date, required: true },
      },
      business: {
        stars: { type: Number, required: true }, // Rating of the business, required for feedback.
        comment: { type: String },
        timestamp: { type: Date, required: true },
      },
      customer: {
        stars: { type: Number, required: true }, // Customer rating, mandatory for transparency.
        comment: { type: String },
        timestamp: { type: Date, required: true },
      },
    },

    timestamps: {
      created: { type: Date, required: true },
      accepted: { type: Date },
      assigned: { type: Date },
      pickedUp: { type: Date },
      delivered: { type: Date },
      cancelled: { type: Date },
    },

    metadata: {
      matchingAlgorithm: { type: String }, // Algorithm used to match rider with delivery.
      cancellationReason: { type: String }, // Reason for cancellation, if applicable.
      disputeId: { type: ObjectId, ref: "Dispute" }, // Reference to a possible dispute associated with the delivery.
      notes: { type: String },
    },
  },
  { timestamps: true } // Automatically adds 'createdAt' and 'updatedAt' fields.
);

const Delivery = mongoose.model("Delivery", DeliverySchema);
export default Delivery;
